const countryCurrency = {
    Afghanistan: { code: "AFN", symbol: "؋" },
    Albania: { code: "ALL", symbol: "L" },
    Algeria: { code: "DZD", symbol: "د.ج" },
    Andorra: { code: "EUR", symbol: "€" },
    Angola: { code: "AOA", symbol: "Kz" },
    AntiguaAndBarbuda: { code: "XCD", symbol: "$" },
    Argentina: { code: "ARS", symbol: "$" },
    Armenia: { code: "AMD", symbol: "֏" },
    Australia: { code: "AUD", symbol: "$" },
    Austria: { code: "EUR", symbol: "€" },
    Azerbaijan: { code: "AZN", symbol: "₼" },
    Bahamas: { code: "BSD", symbol: "$" },
    Bahrain: { code: "BHD", symbol: ".د.ب" },
    Bangladesh: { code: "BDT", symbol: "৳" },
    Barbados: { code: "BBD", symbol: "$" },
    Belarus: { code: "BYN", symbol: "Br" },
    Belgium: { code: "EUR", symbol: "€" },
    Belize: { code: "BZD", symbol: "$" },
    Benin: { code: "XOF", symbol: "CFA" },
    Bhutan: { code: "BTN", symbol: "Nu." },
    Bolivia: { code: "BOB", symbol: "Bs." },
    BosniaAndHerzegovina: { code: "BAM", symbol: "KM" },
    Botswana: { code: "BWP", symbol: "P" },
    Brazil: { code: "BRL", symbol: "R$" },
    Brunei: { code: "BND", symbol: "$" },
    Bulgaria: { code: "BGN", symbol: "лв" },
    BurkinaFaso: { code: "XOF", symbol: "CFA" },
    Burundi: { code: "BIF", symbol: "FBu" },
    Cambodia: { code: "KHR", symbol: "៛" },
    Cameroon: { code: "XAF", symbol: "CFA" },
    Canada: { code: "CAD", symbol: "$" },
    China: { code: "CNY", symbol: "¥" },
    Colombia: { code: "COP", symbol: "$" },
    Croatia: { code: "HRK", symbol: "kn" },
    Cuba: { code: "CUP", symbol: "$" },
    Cyprus: { code: "EUR", symbol: "€" },
    CzechRepublic: { code: "CZK", symbol: "Kč" },
    Denmark: { code: "DKK", symbol: "kr" },
    DominicanRepublic: { code: "DOP", symbol: "$" },
    Egypt: { code: "EGP", symbol: "£" },
    EuroZone: { code: "EUR", symbol: "€" },
    India: { code: "IN", symbol: "₹" },
    Indonesia: { code: "IDR", symbol: "Rp" },
    Iran: { code: "IRR", symbol: "﷼" },
    Iraq: { code: "IQD", symbol: "ع.د" },
    Israel: { code: "ILS", symbol: "₪" },
    Japan: { code: "JPY", symbol: "¥" },
    Jordan: { code: "JOD", symbol: "د.ا" },
    Kazakhstan: { code: "KZT", symbol: "₸" },
    Kenya: { code: "KES", symbol: "KSh" },
    Kuwait: { code: "KWD", symbol: "د.ك" },
    Lebanon: { code: "LBP", symbol: "ل.ل" },
    Malaysia: { code: "MYR", symbol: "RM" },
    Mexico: { code: "MXN", symbol: "$" },
    Nepal: { code: "NPR", symbol: "Rs." },
    Netherlands: { code: "EUR", symbol: "€" },
    NewZealand: { code: "NZD", symbol: "$" },
    Nigeria: { code: "NGN", symbol: "₦" },
    Norway: { code: "NOK", symbol: "kr" },
    Oman: { code: "OMR", symbol: "ر.ع." },
    Pakistan: { code: "PKR", symbol: "₨" },
    Philippines: { code: "PHP", symbol: "₱" },
    Poland: { code: "PLN", symbol: "zł" },
    Qatar: { code: "QAR", symbol: "ر.ق" },
    Russia: { code: "RUB", symbol: "₽" },
    SaudiArabia: { code: "SAR", symbol: "﷼" },
    Singapore: { code: "SGD", symbol: "$" },
    SouthAfrica: { code: "ZAR", symbol: "R" },
    SouthKorea: { code: "KRW", symbol: "₩" },
    SriLanka: { code: "LKR", symbol: "Rs." },
    Sweden: { code: "SEK", symbol: "kr" },
    Switzerland: { code: "CHF", symbol: "CHF" },
    Syria: { code: "SYP", symbol: "£" },
    Taiwan: { code: "TWD", symbol: "NT$" },
    Thailand: { code: "THB", symbol: "฿" },
    Turkey: { code: "TRY", symbol: "₺" },
    Ukraine: { code: "UAH", symbol: "₴" },
    UnitedArabEmirates: { code: "AED", symbol: "د.إ" },
    UnitedKingdom: { code: "GBP", symbol: "£" },
    UnitedStates: { code: "USD", symbol: "$" },
    Venezuela: { code: "VES", symbol: "Bs." },
    Vietnam: { code: "VND", symbol: "₫" },
    Yemen: { code: "YER", symbol: "﷼" },
    Zambia: { code: "ZMW", symbol: "ZK" },
    Zimbabwe: { code: "ZWL", symbol: "$" }
};

export const getCurrencyByCountry = (country) => {
    if (!country) return null;
    const formattedCountry = country.replace(/\s+/g, '');
    return countryCurrency[formattedCountry] || null;
};

export default countryCurrency;
